"""Añadir campos detallados a experiencias, educacion y proyectos

Revision ID: a8481be3b299
Revises: 
Create Date: 2025-07-23 03:21:29.268576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8481be3b299'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('educacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campo_estudio', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('fecha_inicio', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('fecha_fin', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=True))

    with op.batch_alter_table('experiencias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ubicacion', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tipo_empleo', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('fecha_inicio', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('fecha_fin', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=True))

    with op.batch_alter_table('proyectos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asociado_con', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tecnologias', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('enlace_proyecto', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proyectos', schema=None) as batch_op:
        batch_op.drop_column('descripcion')
        batch_op.drop_column('enlace_proyecto')
        batch_op.drop_column('tecnologias')
        batch_op.drop_column('asociado_con')

    with op.batch_alter_table('experiencias', schema=None) as batch_op:
        batch_op.drop_column('descripcion')
        batch_op.drop_column('fecha_fin')
        batch_op.drop_column('fecha_inicio')
        batch_op.drop_column('tipo_empleo')
        batch_op.drop_column('ubicacion')

    with op.batch_alter_table('educacion', schema=None) as batch_op:
        batch_op.drop_column('descripcion')
        batch_op.drop_column('fecha_fin')
        batch_op.drop_column('fecha_inicio')
        batch_op.drop_column('campo_estudio')

    # ### end Alembic commands ###
